### ISSUE TITLE
[FEAT] 작업한 로거와 호환성 만들고 실제 코드 동작 확인하기

### ISSUE THREAD

**Issue by Haneol-Kijm** [boostcampaitech7/level1-imageclassification-cv-21#11]
## Background
- 로거는 민석님이, 코드는 제가 작성하여 추가 작업이 필요합니다.

## Todo
- [x] 작업한 로거와의 호환성 확인
- [x] 실제 코드 동작 확인하기
- [x] 코드 실행할 수 있는 requirements.txt 파일 만들기
- [x] readme.md에 실행 방법 짧게 추가하기
