### ISSUE TITLE
[FEAT] 코드 리팩토링 및 주석 한글화

### ISSUE THREAD

**Issue by Haneol-Kijm** [boostcampaitech7/level1-imageclassification-cv-21#20]
## Background
- 코드의 원활한 이해를 위해 리팩토링 및 주석 추가, 주석 한글화 등이 필요

## Todo
- [x] 코드 리팩토링
- [x] Lightning과 Ray의 파일 저장 경로 정리하기
- [ ] 커맨드라인 편집 옵션 추가
- [ ] 기능별 주석 추가
- [ ] 주석 한글화
- [x] 백그라운드 실행 옵션 추가
