### ISSUE TITLE
[FEAT] 기본 config 변경

### ISSUE THREAD

**Issue by Haneol-Kijm** [boostcampaitech7/level1-imageclassification-cv-21#47]
## Background
- 연구하는 모델 범위가 좁혀짐에 따라 기본 config를 몇 가지 수정합니다.

## Todo
- [x] Dataloader가 processed 폴더와 csv를 참조하도록 변경
- [x] config에서 학습률을 0.002 이하를 갖도록 조정
- [x] 모델 사이즈가 커짐에 따라 배치 사이즈를 낮게 고정
