### ISSUE TITLE
[FEAT] 깃헙 이슈 및 PR 템플릿 만들기

### ISSUE THREAD

**Issue by Haneol-Kijm** [boostcampaitech7/level1-imageclassification-cv-21#5]
## Background
- 깃허브 이슈 템플릿 및 풀리퀘스트(PR) 템플릿 만들기

## Todo
- [x] Feature Request 이슈 템플릿 만들기
- [x] Bug Report 이슈 템플릿 만들기
- [x] Pull Request 템플릿 만들기
