### ISSUE TITLE
[FEAT] 현대 딥러닝에 쓰이는 Augment 방식 총동원 하기

### ISSUE THREAD

**Issue by Haneol-Kijm** [boostcampaitech7/level1-imageclassification-cv-21#56]
## Background
- 현재 Augmentation 갯수가 너무 모자란 것을 논문 보던 와중에 확인함

## Todo
- [x] Label Smoothing 옵션 추가
- [x] AutoAugmentation 옵션 추가
- [x] Mixup+Cutmix 통합으로 쓰는 기능 추가
- [x] LearningRate sheduler cosine+linear 추가
- [ ] 가능하면 ema 추가

## See also
- https://github.com/facebookresearch/deit/blob/main/main.py
