### ISSUE TITLE
[FEAT] 최종 accuracy 상승을 위한 과적합 방지 테크닉

### ISSUE THREAD

**Issue by Haneol-Kijm** [boostcampaitech7/level1-imageclassification-cv-21#62]
## Background
- pretrained DeiT3의 test accuracy가 85%로 나타남에 따라, 더 높은 accuracy를 위한 과적합 방지 기술들을 적용해야할 것으로 예상됨

## Todo
- [ ] Head를 제외한 Model Freeze 기능을 각 모델별로 선택 사항으로 넣을 것인지 고려
- [ ] val_acc를 우선하여 checkpoint가 저장되도록 코드를 수정
- [x] Freeze 없이 fine tuning을 진행하는 사람들을 위해 Drop path를 추가할 것인지 상의
- [ ] 더 추가할 수 있는 기술이 없는지 논문과 코드를 찾아보기

## See also
- #58
