### ISSUE TITLE
[FEAT] TrivialAugmentWide 추가

### ISSUE THREAD

**Issue by boyamie** [boostcampaitech7/level1-imageclassification-cv-21#64]
## Background
- Trivial Augment 도입

## Todo
- [x] Transforms.py에 class TrivialTransform 추가
- [x] Transforms.py에 class TransformSelector 수정
- [x] config.py 수정

## See also
- #
