### ISSUE TITLE
[FEAT] Add Model SwinV2

### ISSUE THREAD

**Issue by kimmaru** [boostcampaitech7/level1-imageclassification-cv-21#79]
## Background
- Add Model SwinV2

## Todo
- [ ] Add SwinV2.py file
- [ ] Add swinv2_config.py
- [ ] Add input_size dict on custom_nn_config.search_space
- [ ] Add model dict on config_factory.CONFIG_MAP
